@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor User
User -> UpdateUser: registrarme(data)
UpdateUser -> NicknameValidator: validate(data)
NicknameValidator --> UpdateUser
UpdateUser -> UserRepository: save()
UserRepository --> UpdateUser
@enduml