@startuml
'https://plantuml.com/sequence-diagram

actor User
User -> UpdateUser: registrarme(data)
UpdateUser -> UpdateUser: validate(data)
UpdateUser -> UserRepository: save(user)
UserRepository --> UpdateUser
UserRepository --> Persistence: save(user, typoPersistencia)
Persistence --> InMemory: save(user)
Persistence --> MySql: save(user)

@enduml